### ISSUE TITLE
c_wr register is not resetable

### ISSUE THREAD

**Issue by mo-hosni** [shalan/MS_SPI_XIP_CACHE#1]
c_wr register is not resetable here:

https://github.com/shalan/MS_SPI_XIP_CACHE/blob/51d9743a31f3241e9f59ac25135df22bfbc46f0f/hdl/rtl/bus_wrapper/MS_SPI_XIP_CACHE_ahbl.v#L148

**Comment by shalan** [comment]
Fixed in  c6ada47
